### ISSUE TITLE
Blur event not firing

### ISSUE THREAD

**Issue by medienbaecker** [TimOetting/kirby-color#10]
When focusing another field to blur the color picker, the blur event does not trigger. To hide the color picker you will then have to re-focus the field and click somewhere else:

![colorpicker-blur](https://user-images.githubusercontent.com/7975568/66210180-7fdc6800-e6b9-11e9-82f1-98ca417b7537.gif)

**Comment by VIPStephan** [comment]
To add to this issue, if I bring up the color picker and click anywhere in it (except the RGB/HSL/HEX input fields at the bottom), the shadow around the color picker disappears, along with the focus outline around the color field, and if I then try to focus one of the RGB/HSL/HEX input fields, the entire color picker disappears. It should stay visible if I want to focus one of these color picker inputs.

**Comment by arnoson** [comment]
In Kirby 3.5 the colorpicker stays open unless I click the small color panel (tested in the latest version of Firefox)
