### ISSUE TITLE
Bug with editableAlpha: false

### ISSUE THREAD

**Issue by VIPStephan** [TimOetting/kirby-color#11]
If `editableAlpha: false` is set, the RGB and HSL modes of the color picker show “RGA” and “HSA” instead, i. e. it seems like the third field is hidden (i. e. “blue” in RGB mode and “lightness” in HSL mode) and the field for the alpha channel is still shown instead (albeit not properly usable).

**Comment by TimOetting** [comment]
Fixed with Version 1.0.1
