### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by jesuismaxime** [TimOetting/kirby-color#7]
Any plan to release it on composer ?

**Comment by tobystokes** [comment]
works via @sylvainjule's fork at
https://github.com/sylvainjule/kirby-color/
Though as it's unreleased, you'll need 
```
{
  "require": {
    "timoetting/kirby-color": "dev-master"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:sylvainjule/kirby-color.git"
    }
  ]
}
```

**Comment by bnomei** [comment]
any news on a packagist release?

**Comment by TimOetting** [comment]
Composer support has been added
